version: '3.4'

services:
  mssqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  myidentity:
    image: ${DOCKER_REGISTRY-}myidentity
    build:
      context: .
      dockerfile: MyIdentity/Dockerfile
    depends_on:
      - mssqldata

  myecommerce-product-api:
    image: ${DOCKER_REGISTRY-}myecommerceproductapi
    build:
      context: .
      dockerfile: MyEcommerce-product-api/Dockerfile
    depends_on:
      - mssqldata
      - myidentity
